In [29]:
import numpy as np
import tensorflow as tf

tf.enable_eager_execution()

# 1- Graph and Session

https://www.easy-tensorflow.com/tf-tutorials/basics/graph-and-session

In [6]:
# Define a Python function.
def a_regular_function(x, y, b):
  x = tf.matmul(x, y)
  x = x + b
  return x

# `a_function_that_uses_a_graph` is a TensorFlow `Function`.
a_function_that_uses_a_graph = tf.function(a_regular_function)

# Make some tensors.
x1 = tf.constant([[1.0, 2.0]])
y1 = tf.constant([[2.0], [3.0]])
b1 = tf.constant(4.0)

orig_value = a_regular_function(x1, y1, b1).numpy()
# Call a `Function` like a Python function.
tf_function_value = a_function_that_uses_a_graph(x1, y1, b1).numpy()
assert(orig_value == tf_function_value)

In [7]:
x1

<tf.Tensor: id=16, shape=(1, 2), dtype=float32, numpy=array([[1., 2.]], dtype=float32)>

In [8]:
y1

<tf.Tensor: id=17, shape=(2, 1), dtype=float32, numpy=
array([[2.],
       [3.]], dtype=float32)>

In [9]:
b1

<tf.Tensor: id=18, shape=(), dtype=float32, numpy=4.0>

In [10]:
orig_value

array([[12.]], dtype=float32)

In [11]:
tf_function_value

array([[12.]], dtype=float32)

# What is a TensorFlow Session?

https://danijar.com/what-is-a-tensorflow-session/

In [12]:
graph = tf.Graph()
with graph.as_default():
  variable = tf.Variable(42, name='foo')
  initialize = tf.global_variables_initializer()
  assign = variable.assign(13)

In [14]:
graph.get_all_collection_keys()

['variables', 'trainable_variables']

In [15]:
with tf.Session(graph=graph) as sess:
  sess.run(initialize)
  sess.run(assign)
  print(sess.run(variable))


13


In [17]:
with tf.Session(graph=graph) as sess:
  print(sess.run(variable))

FailedPreconditionError: Attempting to use uninitialized value foo
	 [[{{node _retval_foo_0_0}}]]

In [18]:
with tf.Session(graph=graph) as sess:
    sess.run(initialize)
    print(sess.run(variable))

42


In [19]:
with tf.Session(graph=graph) as sess:
    sess.run(initialize)
    sess.run(assign)
    print(sess.run(variable))

13


In [20]:
import random


In [22]:
pop = list(i for i in range (11))

In [26]:
random.sample(pop, 5)

[3, 10, 5, 2, 0]

In [27]:
pop1 = list(i for i in range(5, 16))

In [28]:
set(pop) ^ set(pop1)

{0, 1, 2, 3, 4, 11, 12, 13, 14, 15}

# Tensorflow functions/methods/etc.

In [45]:
tf.disable_eager_execution()
is_code_input = tf.placeholder(tf.bool)

In [47]:
print(is_code_input.get_shape())

<unknown>


In [48]:
tf.cond(is_code_input, lambda: 1, lambda: 2)

<tf.Tensor 'cond_4/Merge:0' shape=() dtype=int32>

Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/Users/ggraham/anaconda3/envs/vae/lib/python3.7/site-packages/tensorflow_core/python/autograph/pyct/compiler.py", line 103, in <lambda>
    atexit.register(lambda: os.remove(f.name))
FileNotFoundError: [Errno 2] No such file or directory: '/var/folders/0g/yb4jvrmj2xd0lm1nfx1styjm000_kw/T/tmpxlwyju1a.py'
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/Users/ggraham/anaconda3/envs/vae/lib/python3.7/site-packages/tensorflow_core/python/autograph/pyct/compiler.py", line 103, in <lambda>
    atexit.register(lambda: os.remove(f.name))
FileNotFoundError: [Errno 2] No such file or directory: '/var/folders/0g/yb4jvrmj2xd0lm1nfx1styjm000_kw/T/tmpfw1z83d9.py'
